# Install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
	# configure vagrant box to Ubuntu 18.04
	config.vm.box = "ubuntu/bionic64"

	# configure network ip and hostname alias
	config.vm.network "private_network", ip: "192.168.10.100"
	config.hostsupdater.aliases = ["development.local"]

	# sync folders to VM
	config.vm.sync_folder "/app", "app"
	config.vm.sync_folder "/environment", "environment"
end